stages:
  ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
    - src/components/data_ingestion.py
    - data/data.csv
    outs:
    - artifacts/data_ingestion//train.csv
    - artifacts/data_ingestion//test.csv

  validation:
    cmd: python src/components/data_validation.py
    deps:
    - src/components/data_validation.py
    - artifacts/data_ingestion//train.csv
    - artifacts/data_ingestion//test.csv
    - config/schema.yaml
    outs:
    - artifacts/data_validation/validated_train.csv
    - artifacts/data_validation/validated_test.csv
    - artifacts/data_validation/validation_report.json


  transformation:
    cmd: python src/components/data_transformation.py
    deps:
    - src/components/data_transformation.py
    - artifacts/data_validation/validated_train.csv
    - artifacts/data_validation/validated_test.csv
    - config/schema.yaml
    outs:
    - artifacts/transformation/X_train.npy
    - artifacts/transformation/y_train.npy
    - artifacts/transformation/X_test.npy
    - artifacts/transformation/y_test.npy
    - artifacts/transformation/scaler.pkl

  model_training:
    cmd: python src/components/model_training.py
    deps:
      - src/components/model_training.py
      - artifacts/transformation/X_train.npy
      - artifacts/transformation/y_train.npy
      - artifacts/transformation/X_test.npy
      - artifacts/transformation/y_test.npy
    outs:
      - artifacts/model_training/model.h5
    metrics:
      - artifacts/model_training/metrics.json
