stages:
  ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - data/data.csv
    outs:
      - artifacts/train.csv
      - artifacts/test.csv

  validation:
    cmd: python src/components/data_validation.py
    deps:
      - src/components/data_validation.py
      - artifacts/train.csv
      - artifacts/test.csv
      - config/schema.yaml
    outs:
      - artifacts/validated_train.csv
      - artifacts/validated_test.csv
      - artifacts/validation_report.json
